spring.application.name=DemoWeb

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:DemoWeb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 1. Clean the database on every start
spring.jpa.hibernate.ddl-auto=create-drop

# 2. Run data.sql AFTER Hibernate creates the table
spring.jpa.defer-datasource-initialization=true

# 3. Show SQL in logs (very helpful for debugging)
logging.level.org.hibernate.SQL=DEBUG
#app.security.username=user
#app.security.password={noop}user

